test_that("test decision table generated by mTPI method", {
  

  #
  ex_dtab1 <- matrix(NA, ncol = 10, nrow = 11)
  ex_dtab1[1:2,   1] <- c("E", "D")
  ex_dtab1[1:3,   2] <- c("E", "S", "D")
  ex_dtab1[1:4,   3] <- c("E", "S", "D", "DU")
  ex_dtab1[1:5,   4] <- c("E", "S", "S", "DU", "DU")
  ex_dtab1[1:6,   5] <- c("E", "S", "S", "D",  "DU", "DU")
  ex_dtab1[1:7,   6] <- c("E", "E", "S", "S",  "DU", "DU", "DU")
  ex_dtab1[1:8,   7] <- c("E", "E", "S", "S",  "D",  "DU", "DU", "DU")
  ex_dtab1[1:9,   8] <- c("E", "E", "S", "S",  "D",  "DU", "DU", "DU", "DU")
  ex_dtab1[1:10,  9] <- c("E", "E", "S", "S",  "S",  "DU", "DU", "DU", "DU", "DU")
  ex_dtab1[1:11, 10] <- c("E", "E", "S", "S",  "S",  "D",  "DU", "DU", "DU", "DU", "DU")
  
  
  x1 <- mtpi2_decision_matrix(cocap = 10, target = 0.3, a = 1, b = 1, tolerance1 = 0.05, tolerance2 = 0.05, tox = 0.95, method = "mtpi")
  expect_equal(x1, ex_dtab1)
  
  
  # example in the table using mTPI2 method from the mTPI2 paper
  ex_dtab <- matrix(NA, ncol = 10, nrow = 11)
  ex_dtab[1:2,   1] <- c("E", "D")
  ex_dtab[1:3,   2] <- c("E", "D", "D")
  ex_dtab[1:4,   3] <- c("E", "S", "D", "DU")
  ex_dtab[1:5,   4] <- c("E", "S", "D", "DU", "DU")
  ex_dtab[1:6,   5] <- c("E", "E", "D", "D",  "DU", "DU")
  ex_dtab[1:7,   6] <- c("E", "E", "S", "D",  "DU", "DU", "DU")
  ex_dtab[1:8,   7] <- c("E", "E", "S", "D",  "D",  "DU", "DU", "DU")
  ex_dtab[1:9,   8] <- c("E", "E", "S", "D",  "D",  "DU", "DU", "DU", "DU")
  ex_dtab[1:10,  9] <- c("E", "E", "E", "S",  "D",  "DU", "DU", "DU", "DU", "DU")
  ex_dtab[1:11, 10] <- c("E", "E", "E", "S",  "D",  "D",  "DU", "DU", "DU", "DU", "DU")
  
  x2 <- mtpi2_decision_matrix(cocap = 10, target = 0.3, a = 1, b = 1, tolerance1 = 0.05, tolerance2 = 0.05, tox = 0.95, method = "mtpi2")
  expect_equal(x2, ex_dtab)
  
  
  # understanding the algorithm: The folloiwng code demonstrate the example in
  # the paper, when you see 3 out of 6 subjects having DLT, mTPI says "S" while
  # mTPI2 says "D"
  # x <- 3; n <- 6;
  # a <- 1; b <- 1; # prior
  # # posterior parameters
  # pos_a <- a + x; pos_b <- n - x + b; c(pos_a, pos_b)
  # tolerance1 <- 0.05; tolerance2 <- 0.05; target <- 0.3
  # pt1 <- target - tolerance1; pt2 <- target + tolerance2
  # 
  # # under mTPI1
  # intv <- c(0, pt1, pt2, 1)
  # intv_l <- diff(intv)
  # sr1 <- pbeta(intv[-1], shape1 = pos_a, shape2 = pos_b) - pbeta(intv[1:(length(intv)-1)], shape1 = pos_a, shape2 = pos_b)
  # upm <- sr1 /intv_l # probability divided by interval length
  # 
  # # for mTPI2, the intervals are further divided so each interval (except head and tail) have equal length
  # intv2 <- c(0, seq(0.05, 0.95, by = 0.1), 1)
  # 
  # sr2 <- pbeta(intv2[-1], shape1 = 4, shape2 = 4) - pbeta(intv2[1:11], shape1 = 4, shape2 = 4)
  # upm2 <- sr2/diff(intv2)
  # which.max(upm2); cut(intv2, breaks = c(-1, pt1, pt2, 1))
  # 
  
})
